theme: minima
title: Github Pages
author: wmcdonald404  

minima:
  skin: solarized-light
  social_links:
    - { platform: github,         user_url: "https://github.com/wmcdonald404" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/willmcd" }
    # - { platform: bluesky,        user_url: "https://bsky.app/profile/wmcdonald404.bsky.social" }

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      isPost: true
      layout: post
  -
    scope:
      type: recipes
      path: _recipes
    values:
      layout: post

collections:
  recipes:
    output: true      
